### PR TITLE
Parse shapes.txt file

### PR DESCRIPTION
**Pull request by cedarbaum**
Parse shapes.txt files. This helps make progress on #4.

### CODE REVIEW

**Comment by cedarbaum** [comment]
It occurs to me now that it makes more sense to include the associated shape directly in the trip it describes. I can make this change in the next iteration if that design sounds good.

**Comment by jamespfennell** [comment]
Looks great to me!

Regarding the trip-shape relationship, this would be good to have (but feel free to do in a follow up? In which case could submit this right now). From [the GTFS static reference](https://developers.google.com/transit/gtfs/reference#tripstxt) it seems the relationship is many trips to one shape. I guess the way to model this here would be to have a new `*Shape` field on the trip that is a pointer into the shapes array. Maybe it would make sense to parse shapes _before_ parsing trips, and as well as constructing `[]Shape` we would also construct a `map[string]*Shape` mapping shape IDs to a pointer to the share in the slice? Then when parsing trips we could check the array to see if there is a shape.

Nice one!

**Comment by cedarbaum** [comment]
I went ahead and added the `Shape` pointers directly to the `ScheduledTrip` objects.

**Comment by cedarbaum** [comment]
I suppose we could also still return `Shapes` in the top-level `Static` struct as well (similar to how `Services` is handled). Let me know if you think that still makes sense, should be easy to quickly re-add it there too.

**Comment by cedarbaum** [comment]
That makes sense, thanks! I do want to eventually use this data in Transiter, so have added it back to the `Static` struct as well in latest commit.

**Comment by jamespfennell** [comment]
Awesome!

**Pull request merged**
